Improves
yobta/generator pull request #12
Opened 2023-09-18 13:18 UTC by plusbpm

2023-09-18 16:10 UTC, droganov requested changes

2023-09-18 16:10 UTC, droganov commented on package.json
> +        "swr": "^2.2.0"
в данном случае это дев завиимость, ты не пользуешся свр а только его тип тебе нужен

2023-09-18 16:10 UTC, droganov commented on docs/in-code-usage.md
> +  return useSWR([url, init], fetch) as HookResult<any>
as HookResult<any> больше не нужн, должно и без него работать

2023-09-19 05:40 UTC, plusbpm commented on package.json
> +        "swr": "^2.2.0"
переместил в dev

2023-09-19 05:41 UTC, plusbpm commented on docs/in-code-usage.md
> +  return useSWR([url, init], fetch) as HookResult<any>
Без него не работает, тайпскрипт дает ошибку сужения типа

2023-09-19 05:49 UTC, plusbpm commented on docs/in-code-usage.md
> +  return useSWR([url, init], fetch) as HookResult<any>
убрал HookResult

2023-09-19 08:20 UTC, droganov approved these changes

2023-09-19 08:21 UTC, merged